### ISSUE TITLE
"file not found" when using IAM_KEY authentication

### ISSUE THREAD

**Issue by kbiegertibm** [glynnbird/couchimport#181]
Fresh install of couchimport.
Verified all runs well when using id and password authentication.

Trying to use IAM_KEY auth.

1. export IAM_API_KEY=<value from my cloudant service credentials 'apikey'>
2. run couchimport

get the following:

couchimport
-----------
 url         : "https://6f0e3c7d-3b09-4fd0-b253-c26d43892ac6-bluemix.cloudantnosqldb.appdomain.cloud"
 database    : "unlocodes_data"
 delimiter   : "\t"
 buffer      : 500
 parallelism : 1
 type        : "jsonl"
-----------
Error: ENOENT: no such file or directory, open '/Users/kbiegert/.ccurl/keycache.json'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at Object.init (/usr/local/Cellar/node/13.8.0/lib/node_modules/couchimport/node_modules/ccurllib/index.js:21:20)
    at Object.getToken (/usr/local/Cellar/node/13.8.0/lib/node_modules/couchimport/includes/iam.js:5:14)
    at module.exports (/usr/local/Cellar/node/13.8.0/lib/node_modules/couchimport/includes/writer.js:20:7)
    at Object.importStream (/usr/local/Cellar/node/13.8.0/lib/node_modules/couchimport/app.js:22:49)
    at Object.<anonymous> (/usr/local/Cellar/node/13.8.0/lib/node_modules/couchimport/bin/couchimport.bin.js:48:15)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/kbiegert/.ccurl/keycache.json'
}
events.js:298
      throw er; // Unhandled 'error' event
      ^

Error [ERR_METHOD_NOT_IMPLEMENTED]: The _transform() method is not implemented
    at Transform._transform (_stream_transform.js:166:6)
    at Transform._read (_stream_transform.js:191:10)
    at Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at Transform.Writable.write (_stream_writable.js:316:11)
    at Transform.ondata (_stream_readable.js:714:22)
    at Transform.emit (events.js:321:20)
    at addChunk (_stream_readable.js:294:12)
    at readableAddChunk (_stream_readable.js:275:11)
Emitted 'error' event on Transform instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at Transform.onerror (_stream_readable.js:746:7)
    at Transform.emit (events.js:321:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:456:5)
    at onwrite (_stream_writable.js:483:5)
    at Transform.afterTransform (_stream_transform.js:98:3)
    at Transform._transform (_stream_transform.js:166:3)
    at Transform._read (_stream_transform.js:191:10)
    at Transform._write (_stream_transform.js:179:12) {
  code: 'ERR_METHOD_NOT_IMPLEMENTED'
}

**Comment by kbiegertibm** [comment]
Also not sure about the transform error.  I did not specify a transform function as I do not need any transformations to be done and I believed this to be optional.  Thank you for the help.

**Comment by glynnbird** [comment]
Thanks for reporting this. I've fixed it in v1.4.4 so if you reinstall, this should go away.
